stages:
  - linting
  - simulation


verilator:verilog:
  image: localhost:5000/lagarto_rtl 
  stage: linting
  script:
    - verilator --version
    - make lint
  allow_failure: true

spyglass:verilog:
  image: localhost:5000/epi_rtl-spyglass-lint
  stage: linting
  tags:
    - spyglass
  script:
    - make local_spyglass
  allow_failure: true

  artifacts:
    paths:
    - top_drac/consolidated_reports/top_drac_lint_lint_rtl/
    expire_in: 1 week

#questa:verilog:
#  image: localhost:5000/epi_rtl-vsim
#  stage: simulation
#  tags:
#    - questasim
#  script:
#    - make questa
#  allow_failure: true
#
#  artifacts:
#    paths:
#    - artifact_questa.log
#    expire_in: 1 week

