image: localhost:5000/lagarto_rtl 

stages:
  - verilator
  - spyglass

verilator:verilog:
  stage: verilator
  script:
    - verilator --version
    - make lint
  allow_failure: true

image: localhost:5000/epi_rtl-spyglass-lint
spyglass:verilog:
  stage: spyglass
  tags:
    - spyglass
  script:
    - make local_spyglass
  allow_failure: true

  artifacts:
    paths:
    - top_drac/consolidated_reports/top_drac_lint_lint_rtl/
    expire_in: 1 week
