image: localhost:5000/lagarto_rtl 

before_script:
  - apt update
  - apt install verilator -y

stages:
  - verilator
  - spyglass

verilator:verilog:
  stage: verilator
  script:
    - verilator --version
    - make lint

image: localhost:5000/epi-vector-lint:latest
spyglass:verilog:
  stage: spyglass
  tags:
    - spyglass
  script:
    - make local_spyglass
  allow_failure: true
